---
permalink: online-help/concept-managing-reports.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager vous permet de créer et de gérer des rapports directement depuis l"interface utilisateur Unified Manager. Ainsi, vous pouvez afficher des informations sur les relations entre l"état, la capacité, les performances et la protection des objets de stockage dans les clusters. La consultation de ces informations peut vous aider à identifier les problèmes potentiels avant qu"ils ne surviennent.' 
---
= Gestion des rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager vous permet de créer et de gérer des rapports directement depuis l'interface utilisateur Unified Manager. Ainsi, vous pouvez afficher des informations sur les relations entre l'état, la capacité, les performances et la protection des objets de stockage dans les clusters. La consultation de ces informations peut vous aider à identifier les problèmes potentiels avant qu'ils ne surviennent.

Vous pouvez télécharger des rapports sous forme de valeurs séparées par des virgules (.csv), Microsoft Excel (.xlsx) ou des fichiers PDF. Vous pouvez également planifier l'envoi d'un rapport par e-mail à un groupe de destinataires. Les rapports sont envoyés sous forme de pièces jointes.

Outre la génération de rapports depuis l'interface utilisateur, vous pouvez extraire les données de santé et de performances à partir d'Unified Manager en utilisant les méthodes suivantes :

* Utilisation des outils ODBC (Open Database Connectivity) et ODBC pour accéder directement à la base de données pour les informations de cluster
* Exécution d'API REST Unified Manager pour renvoyer les informations que vous souhaitez consulter


À partir de cette version de Active IQ Unified Manager, les améliorations suivantes sont apportées aux rapports :

* Un e-mail est envoyé pour un rapport conformément à l'horaire configuré. Même si vous générez un rapport à la demande, vous recevrez un e-mail.
* Le nom du fichier du rapport et les métadonnées du rapport incluent le nom d'hôte à partir duquel le rapport a été généré.
+
Même si un changement de nom de fichier change, vous pouvez toujours identifier le nom d'hôte à partir duquel le rapport a été généré en raison de cette amélioration.


