---
permalink: online-help/concept-nvme-namespace-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 'La page NVMe namespace/Performance Explorer fournit une présentation détaillée des performances de tous les espaces de noms NVMe au sein d"un cluster.' 
---
= Espace de noms NVMe/Explorateur de performances
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page NVMe namespace/Performance Explorer fournit une présentation détaillée des performances de tous les espaces de noms NVMe au sein d'un cluster.

La page NVMe namespace/Performance Explorer vous permet de suivre et de comparer les performances de l'espace de noms NVMe pendant une période donnée. Ceci vous aide à résoudre les problèmes et à ajuster les performances de vos espaces de noms.

La fonctionnalité View and compare vous permet de comparer les performances de ce namespace NVMe avec :

* Volume sur lequel réside le namespace
* Autres espaces de noms sur le même volume
* Autres espaces de noms se trouvant sur la même machine virtuelle de stockage


Avec la page de l'explorateur de performances/namespace NVMe, vous pouvez :

* Afficher les problèmes liés aux seuils et leurs détails
* Suivez et comparez les données de performances de l'espace de noms
* Examiner et résoudre les problèmes liés aux seuils
* Examiner et résoudre les problèmes de performances
* Lancer System Manager pour modifier la configuration dans l'espace de noms
+
Le bouton *configurer l'espace de noms NVMe* est disponible si vous êtes connecté à Unified Manager avec le rôle Administrateur d'applications ou Administrateur de stockage, et si vous utilisez ONTAP 9.5 ou une version ultérieure.


