---
permalink: online-help/concept-security-dashboard.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez activer ou désactiver le panneau sécurité sur le tableau de bord Active IQ Unified Manager. Lorsque cette option est activée, vous pouvez également personnaliser les paramètres de contrôle de la conformité ainsi que les événements de sécurité et les actions de gestion pertinentes. 
---
= Tableau de bord de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver le panneau sécurité sur le tableau de bord Active IQ Unified Manager. Lorsque cette option est activée, vous pouvez également personnaliser les paramètres de contrôle de la conformité ainsi que les événements de sécurité et les actions de gestion pertinentes.

[NOTE]
====
Seuls les utilisateurs disposant d'un rôle d'administrateur peuvent modifier ces paramètres.

====
Les critères de sécurité des clusters ONTAP, des machines virtuelles de stockage et des volumes sont évalués sur la base des recommandations définies dans le guide NetApp de renforcement de la sécurité des environnements ONTAP 9. Le panneau de sécurité du tableau de bord affiche l'état de conformité de sécurité de vos clusters, machines virtuelles de stockage et volumes. L'activation de cette fonctionnalité génère également des événements de sécurité pour tout cluster ou machine virtuelle de stockage qui a des violations de sécurité.



== Personnalisation des paramètres

Lors de l'activation de cette fonction, vous pouvez personnaliser les paramètres de contrôle de conformité, selon votre environnement ONTAP. Ces paramètres déclenchent les événements de sécurité et les actions de gestion pertinentes. Voici la procédure à suivre :

. Cliquez sur *Personnaliser*. La fenêtre contextuelle Personnaliser les paramètres du tableau de bord de sécurité s'affiche.
. Pour activer ou désactiver les paramètres personnalisés de vos clusters ONTAP, développez la sélection *Paramètres généraux* pour les clusters. Pour plus d'informations sur les options de personnalisation de la conformité des clusters, reportez-vous à la section link:reference-cluster-compliance-categories.adoc["*Catégories de conformité de groupe*"].
. Pour activer ou désactiver les paramètres personnalisés de vos machines virtuelles de stockage, développez la sélection *Paramètres généraux* pour les machines virtuelles de stockage. Pour plus d'informations sur les options de personnalisation de la conformité de la VM de stockage, reportez-vous à la section link:reference-svm-compliance-categories.adoc["Catégories de conformité des VM de stockage"].
. Vous pouvez également indiquer si le transport HTTPS est utilisé pour l'envoi des messages AutoSupport depuis ONTAP.
. Si vous activez les paramètres d'authentification, les alertes sont envoyées depuis Unified Manager pour l'utilisateur administrateur ONTAP par défaut.

