---
permalink: online-help/reference-performance-all-nvme-namespaces-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue Performance : tous les espaces de noms NVMe présente les événements de performance, les données et les informations de configuration de chaque espace de nom NVMe surveillé par une instance de Unified Manager. Cela vous permet de surveiller rapidement les performances et l"intégrité de vos espaces de noms, et de résoudre les problèmes et les événements de seuils.' 
---
= Performance : vue de tous les espaces de noms NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue Performance : tous les espaces de noms NVMe présente les événements de performance, les données et les informations de configuration de chaque espace de nom NVMe surveillé par une instance de Unified Manager. Cela vous permet de surveiller rapidement les performances et l'intégrité de vos espaces de noms, et de résoudre les problèmes et les événements de seuils.

Par défaut, les objets des pages de vue sont triés en fonction de la criticité de l'événement. Les objets avec des événements critiques sont répertoriés en premier et les objets avec des événements d'avertissement sont répertoriés en second. Cela fournit une indication visuelle immédiate des problèmes à résoudre.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Vous pouvez affecter des stratégies de seuil de performances à ou effacer des stratégies de seuil à partir de n'importe quel objet sur les pages d'inventaire des objets à l'aide des boutons *affecter la stratégie de seuil de performances* et *Effacer la stratégie de seuil de performances*.

Voir xref:reference-nvme-namespace-performance-fields.adoc[Champs de performance de l'espace de noms NVMe] pour la description de tous les champs de cette page.
