---
permalink: online-help/reference-health-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue Santé : tous les agrégats affiche des informations sur les agrégats surveillés et vous permet d"afficher et de modifier les paramètres des seuils.' 
---
= Santé : vue de tous les agrégats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue Santé : tous les agrégats affiche des informations sur les agrégats surveillés et vous permet d'afficher et de modifier les paramètres des seuils.

Par défaut, les objets des pages de vue sont triés en fonction de la criticité de l'événement. Les objets avec des événements critiques sont répertoriés en premier et les objets avec des événements d'avertissement sont répertoriés en second. Cela fournit une indication visuelle immédiate des problèmes à résoudre. Chaque agrégat de la grille des agrégats dispose de liens vers ONTAP System Manager. Ce lien vous redirige vers ONTAP System Manager afin d'afficher les mêmes relations de protection.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Vous pouvez personnaliser les paramètres de seuil de capacité pour un ou plusieurs agrégats à l'aide du bouton *Modifier le seuil*.

Voir xref:reference-aggregate-health-fields.adoc[Champs de santé agrégés] pour la description de tous les champs de cette page.
