---
permalink: online-help/reference-performance-all-svms-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue performances : tous les VM de stockage affiche un aperçu des événements de performances, des données et des informations de configuration de chaque VM de stockage \(SVM\) contrôlé par une instance de Unified Manager. Vous pouvez ainsi surveiller rapidement les performances des SVM et résoudre les problèmes de performances et les seuils.' 
---
= Performances : vue de toutes les machines virtuelles de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue performances : tous les VM de stockage affiche un aperçu des événements de performances, des données et des informations de configuration pour chaque SVM (Storage Virtual machine) contrôlé par une instance de Unified Manager. Vous pouvez ainsi surveiller rapidement les performances des SVM et résoudre les problèmes de performances et les seuils.

Par défaut, les objets des pages de vue sont triés en fonction de la criticité de l'événement. Les objets avec des événements critiques sont répertoriés en premier et les objets avec des événements d'avertissement sont répertoriés en second. Cela fournit une indication visuelle immédiate des problèmes à résoudre.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Vous pouvez affecter des stratégies de seuil de performances à ou effacer des stratégies de seuil à partir de n'importe quel objet sur les pages d'inventaire des objets à l'aide des boutons *affecter la stratégie de seuil de performances* et *Effacer la stratégie de seuil de performances*.

[NOTE]
====
Les SVM répertoriés sur cette page incluent uniquement les SVM Data et Cluster. Unified Manager n'utilise ni n'affiche les SVM d'administration ou de nœuds.

====
Voir xref:reference-svm-performance-fields.adoc[Champs de performance des SVM] pour la description de tous les champs de cette page.
