---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 'Le vue capacité : tous les clusters permet d"afficher des informations résumées sur la capacité de stockage et l"utilisation de tous les clusters. Ces informations vous aident à comprendre les risques potentiels en matière de capacité et à prendre les mesures appropriées pour rééquilibrer les charges de travail.' 
---
= Capacité : vue de tous les clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le vue capacité : tous les clusters permet d'afficher des informations résumées sur la capacité de stockage et l'utilisation de tous les clusters. Ces informations vous aident à comprendre les risques potentiels en matière de capacité et à prendre les mesures appropriées pour rééquilibrer les charges de travail.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Voir xref:reference-cluster-capacity-fields.adoc[Champs de la capacité du cluster] pour la description de tous les champs de cette page.
