---
permalink: online-help/reference-lag-thresholds-for-unmanaged-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: 'La page seuils de relation vous permet de configurer les valeurs d"avertissement global de décalage et de seuil d"erreur pour les relations de protection non gérées, de sorte que vous soyez averti et que vous pouvez prendre des mesures en cas d"erreurs de décalage ou de seuil. Les modifications apportées à ces paramètres sont appliquées lors de la prochaine mise à jour programmée.' 
---
= Page seuils de relation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page seuils de relation vous permet de configurer les valeurs d'avertissement global de décalage et de seuil d'erreur pour les relations de protection non gérées, de sorte que vous soyez averti et que vous pouvez prendre des mesures en cas d'erreurs de décalage ou de seuil. Les modifications apportées à ces paramètres sont appliquées lors de la prochaine mise à jour programmée.

Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.

Les événements sont générés lorsqu'un seuil est atteint pour les volumes ou les machines virtuelles de stockage. Vous pouvez prendre des actions correctives pour de tels événements. Ces événements sont maintenant signalés pour les relations des machines virtuelles de stockage, mais ils sont bloqués afin de ne pas établir de relation entre les composants de la configuration de reprise après incident des machines virtuelles de stockage. Cela permet d'éviter que trop d'événements soient soulevés pour une relation. Les paramètres de seuil de décalage des relations non gérées sont activés par défaut et sont également fournis pour les machines virtuelles de stockage.

Le seuil de décalage indique un pourcentage que le temps de décalage ne doit pas dépasser. Par exemple, si le seuil de décalage est défini sur 150 %, vous recevrez un événement lorsque le temps de décalage est supérieur à 1.5 heures.



== Seuils de latence de la zone relations non gérées

La zone de décalage vous permet de définir des seuils de décalage de relation non gérés dans les conditions suivantes :

* *Avertissement*
+
Spécifie le pourcentage auquel la durée de décalage est égale ou supérieure au seuil d'avertissement de décalage :

+
** Valeur par défaut : 150 %
** Événements générés : avertissement de décalage de la relation SnapMirror ou avertissement de décalage de la relation SnapVault
** Gravité de l'événement : avertissement


* *Erreur*
+
Spécifie le pourcentage auquel la durée de décalage est égale ou supérieure au seuil d'erreur de décalage :

+
** Valeur par défaut : 250 %
** Événements générés : erreur de décalage de la relation SnapMirror ou erreur de décalage de la relation SnapVault
** Gravité de l'événement : erreur




En outre, vous pouvez désactiver le déclenchement d'un événement d'avertissement ou d'erreur à partir de n'importe quel seuil de décalage en décochant la case en regard de activé.
