---
permalink: online-help/reference-health-all-nodes-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue Santé : tous les nœuds permet d"afficher des informations détaillées sur les nœuds de tous les clusters gérés par Unified Manager.' 
---
= Santé : vue de tous les nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue Santé : tous les nœuds permet d'afficher des informations détaillées sur les nœuds de tous les clusters gérés par Unified Manager.

Par défaut, les objets des pages de vue sont triés en fonction de la criticité de l'événement. Les objets avec des événements critiques sont répertoriés en premier et les objets avec des événements d'avertissement sont répertoriés en second. Cela fournit une indication visuelle immédiate des problèmes à résoudre. Chaque nœud de la grille nœuds dispose de liens vers ONTAP System Manager. Ce lien vous redirige vers ONTAP System Manager afin d'afficher les mêmes relations de protection.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Dans le menu *Rapports*, l'option *Rapport d'inventaire du matériel* est disponible lorsque Unified Manager et les clusters qu'il gère sont installés sur un site sans connectivité réseau externe. Ce bouton génère un `.csv` fichier qui contient une liste complète d'informations sur le cluster et le nœud, notamment les numéros de modèle du matériel et les numéros de série, les types et le nombre de disques, les licences installées, etc. Cette fonctionnalité de reporting est utile pour le renouvellement de contrats dans des sites sécurisés qui ne sont pas connectés à la plateforme NetAppActive IQ.

Voir xref:reference-node-health-fields.adoc[Champs d'intégrité des nœuds] pour la description de tous les champs de cette page.
