---
permalink: online-help/reference-performance-all-lifs-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue performances : toutes les interfaces réseau affiche un aperçu des événements de performances, des données et des informations de configuration pour chaque interface réseau \(LIF\) surveillée par cette instance de Unified Manager. Cette page vous permet de surveiller rapidement les performances de vos interfaces et de résoudre les problèmes de performances et les événements seuils.' 
---
= Performance : vue de toutes les interfaces réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue performances : toutes les interfaces réseau affiche un aperçu des événements de performances, des données et des informations de configuration pour chaque interface réseau (LIF) surveillée par cette instance de Unified Manager. Cette page vous permet de surveiller rapidement les performances de vos interfaces et de résoudre les problèmes de performances et les événements seuils.

Par défaut, les objets des pages de vue sont triés en fonction de la criticité de l'événement. Les objets avec des événements critiques sont répertoriés en premier et les objets avec des événements d'avertissement sont répertoriés en second. Cela fournit une indication visuelle immédiate des problèmes à résoudre.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Vous pouvez affecter des stratégies de seuil de performances à ou effacer des stratégies de seuil à partir de n'importe quel objet sur les pages d'inventaire des objets à l'aide des boutons *affecter la stratégie de seuil de performances* et *Effacer la stratégie de seuil de performances*.

[NOTE]
====
Les interfaces répertoriées sur cette page incluent les LIFs data, les LIFs Cluster, les LIFs Node Management et les LIF intercluster. Unified Manager n'utilise ni n'affiche les LIF de système.

====
Voir xref:reference-lif-performance-fields.adoc[Champs de performances de l'interface réseau] pour la description de tous les champs de cette page.
