---
permalink: online-help/reference-aggregate-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Les champs suivants sont disponibles dans le rapport capacité globale et utilisation et peuvent être utilisés dans des vues personnalisées et des rapports. 
---
= Champs de capacité d'agrégat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les champs suivants sont disponibles dans le rapport capacité globale et utilisation et peuvent être utilisés dans des vues personnalisées et des rapports.

* *Agrégat*
+
Nom de l'agrégat.

* *Taux de croissance quotidien %*
+
Taux de croissance qui a lieu toutes les 24 heures dans l'agrégat.

* *Jours à plein*
+
Nombre estimé de jours restants avant d'atteindre la capacité totale de l'agrégat.

* *Capacité excédentaire %*
+
Le surengagement global en pourcentage.

* *Données disponibles %*
+
Capacité de données disponible en pourcentage.

* *Capacité de données disponible*
+
Capacité de données disponible.

* *Données utilisées %*
+
Capacité de données utilisée en pourcentage.

* *Capacité de données utilisée*
+
Capacité de données utilisée.

* *Capacité de données totale*
+
Capacité totale des données (utilisée plus disponible).

* *Espace logique utilisé*
+
La taille réelle des données stockées dans l'agrégat sans appliquer les économies obtenues grâce aux technologies d'efficacité du stockage de ONTAP.

* *Réserve Snapshot disponible %*
+
Quantité d'espace disponible pour les copies Snapshot sous forme de pourcentage.

* *Capacité disponible de réserve Snapshot*
+
Quantité d'espace disponible pour les copies Snapshot.

* *La réserve Snapshot utilisée %*
+
Quantité d'espace utilisée par les copies Snapshot à partir de la réserve Snapshot sous forme de pourcentage.

* *Capacité utilisée de réserve Snapshot*
+
Quantité d'espace utilisée par les copies Snapshot à partir de la réserve Snapshot.

* *Capacité totale de la réserve Snapshot*
+
Capacité totale de réserve snapshot de l'agrégat.

* *Espace de Tier de cloud utilisé*
+
Capacité de données actuellement utilisée dans le Tier cloud.

* *Tier cloud*
+
Nom du magasin d'objets du Tier cloud lors de sa création par ONTAP.

* *État*
+
État actuel de l'agrégat.

* *Type*
+
Le type d'agrégat :

+
** DISQUES DURS
** Hybride
+
Combinaison de disques durs et de disques SSD, mais Flash Pool n'a pas été activé.

** Hybride (Flash Pool)
+
Combinaison de disques durs et de disques SSD et Flash Pool est activé.

** SSD
** SSD (FabricPool)
+
Combinaison de SSD et d'un Tier cloud

** HDD (FabricPool)
+
Combinaison de disques durs et d'un Tier cloud

** VMDisk (SDS)
+
Disques virtuels au sein d'une machine virtuelle

** Disque VMware (FabricPool)
+
Combinaison de disques virtuels et d'un niveau cloud

** LUN (FlexArray)


* *Type RAID*
+
Type de configuration RAID.

* *Type SnapLock*
+
Type SnapLock de l'agrégat. Les valeurs possibles sont Compliance, Enterprise, non SnapLock.

* *Paire HA*
+
Valeur de la paire HA obtenue en formant deux nœuds.

* *Nœud*
+
Nom du nœud qui contient l'agrégat.

* *Cluster*
+
Nom du cluster. Vous pouvez cliquer sur le nom du cluster pour accéder à la page des détails sur la capacité du cluster.

* *FQDN du cluster*
+
Nom de domaine complet (FQDN) du cluster.


