---
permalink: online-help/reference-capacity-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue capacité : tous les agrégats vous permet d"afficher des informations sur la capacité et l"utilisation des agrégats de tous les clusters. Ces informations vous permettent de comprendre les risques potentiels en matière de capacité ainsi que d"afficher la capacité configurée, utilisée et inutilisée des agrégats.' 
---
= Capacité : vue de tous les agrégats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue capacité : tous les agrégats vous permet d'afficher des informations sur la capacité et l'utilisation des agrégats de tous les clusters. Ces informations vous permettent de comprendre les risques potentiels en matière de capacité ainsi que d'afficher la capacité configurée, utilisée et inutilisée des agrégats.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

Voir xref:reference-aggregate-capacity-fields.adoc[Champs de capacité d'agrégat] pour la description de tous les champs de cette page.
