---
permalink: online-help/task-viewing-the-volume-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'Depuis la vue Health: All volumes, vous pouvez surveiller votre inventaire des volumes. Le vue capacité : tous les volumes vous permet d"afficher des informations sur la capacité et l"utilisation des volumes d"un cluster.' 
---
= Affichage de la liste des volumes et des détails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la vue Health: All volumes, vous pouvez surveiller votre inventaire des volumes. Le vue capacité : tous les volumes vous permet d'afficher des informations sur la capacité et l'utilisation des volumes d'un cluster.



== Avant de commencer

Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.



== Description de la tâche

Vous pouvez également utiliser la page des détails Volume / intégrité pour afficher des informations détaillées sur les volumes surveillés, notamment la capacité, l'efficacité, la configuration et la protection des volumes. Vous pouvez également afficher des informations sur les périphériques associés et les alertes associées d'un volume spécifique.



== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Storage* > *volumes*.
. Choisissez l'une des méthodes suivantes pour afficher les détails du volume :
+
** Pour afficher des informations détaillées sur l'état de santé des volumes d'un cluster, dans le menu View, sélectionnez Health: All volumes View.
** Pour afficher des informations détaillées sur la capacité et l'utilisation des volumes d'un cluster, sélectionnez la vue Capacity : tous les volumes dans le menu View.
** Pour afficher les informations complètes, cliquez sur le nom du volume.
+
Vous pouvez également afficher les détails complets en cliquant sur *Afficher les détails* dans la boîte de dialogue Détails minimaux.



. Affichez les objets liés au volume en cliquant sur *Afficher les objets associés* dans la boîte de dialogue Détails minimaux.

