---
permalink: online-help/task-viewing-the-svm-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'Depuis la vue Health: All Storage VM, vous pouvez surveiller l"inventaire des machines virtuelles de stockage \(SVM\). Vous pouvez utiliser la page Storage VM / Health pour afficher des informations détaillées sur les SVM surveillés.' 
---
= Affichage de la liste des VM de stockage et des détails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis le point de vue Health: All Storage VM, vous pouvez surveiller l'inventaire des machines virtuelles de stockage (SVM). Vous pouvez utiliser la page Storage VM / Health pour afficher des informations détaillées sur les SVM surveillés.



== Avant de commencer

Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.



== Description de la tâche

Vous pouvez afficher des détails relatifs aux SVM, comme la capacité, l'efficacité et la configuration d'un SVM. Vous pouvez également afficher des informations sur les périphériques associés et les alertes associées pour ce SVM.



== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Storage* > *Storage VM*.
. Choisir l'une des méthodes suivantes pour afficher les détails du SVM :
+
** Pour afficher les informations relatives à l'état de santé de tous les SVM de tous les clusters, dans le menu View, sélectionnez Santé : vue tous les VM de stockage.
** Pour afficher les informations complètes, cliquez sur le nom de la VM de stockage.
+
Vous pouvez également afficher les détails complets en cliquant sur *Afficher les détails* dans la boîte de dialogue Détails minimaux.



. Afficher les objets liés à la SVM en cliquant sur *View Related* dans la boîte de dialogue des détails minimaux.

