---
permalink: online-help/task-monitoring-storage-vms-using-relationships-page.html 
sidebar: sidebar 
keywords: Relationships page,monitor storage VMs 
summary: 'Vous pouvez surveiller vos relations de reprise après incident de machine virtuelle de stockage depuis la page relations de la section PROTECTION de l"INVENTAIRE. Par défaut, la page relations répertorie uniquement les relations de niveau supérieur car le filtre relations composant est appliqué.' 
---
= Surveillance des VM de stockage à l'aide de la page relations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez surveiller vos relations de reprise après incident de machine virtuelle de stockage depuis la page relations de la section PROTECTION de l'INVENTAIRE. Par défaut, la page relations répertorie uniquement les relations de niveau supérieur car le filtre relations composant est appliqué.



== Avant de commencer

Vous devez avoir le rôle Administrateur d'applications ou Administrateur de stockage.



== Description de la tâche

Vous utilisez des filtres pour afficher les relations de reprise après incident des machines virtuelles de stockage.



== Étapes

. Dans le volet de navigation de gauche, cliquez sur *PROTECTION* > *relations*.
+
La page affiche tous les types de relations : relations de volume et de stockage des machines virtuelles.

. Cliquez sur *Filter*, puis sélectionnez *Relationship Object Type* et *Storage VM* pour afficher uniquement les relations de reprise après sinistre des VM de stockage.
. Cliquez sur *appliquer le filtre*.
+
[NOTE]
====
Vous devez effacer le filtre des relations constituant pour afficher toutes les relations de protection.

====
+
La page affiche uniquement les relations de reprise après incident des machines virtuelles de stockage.


