---
permalink: online-help/task-unconfiguring-netapp-snapshot-backup.html 
sidebar: sidebar 
keywords: NetApp Snapshot Backup for Windows,Unconfigure 
summary: 'Pour modifier le type de sauvegarde de votre système Active IQ Unified Manager, vous pouvez utiliser les options de la console de maintenance. L"option Unconfigure NetApp Snapshot Backup vous permet de revenir à la sauvegarde MySQL.' 
---
= Modification du type de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour modifier le type de sauvegarde de votre système Active IQ Unified Manager, vous pouvez utiliser les options de la console de maintenance. L'option Unconfigure NetApp Snapshot Backup vous permet de revenir à la sauvegarde MySQL.



== Avant de commencer

Vous devez disposer d'un ID utilisateur et d'un mot de passe autorisés pour vous connecter à la console de maintenance du serveur Unified Manager.



== Étapes

. Accéder à la console de maintenance.
. Sélectionnez `4` À partir du *Menu principal* pour la restauration en arrière.
. Sélectionnez `2` Dans le menu *Sauvegarder et Restaurer*.
. Sélectionnez `4` Pour *Unconfigure NetApp Snapshot Backup*.
+
Les actions exécutées sont affichées, qui sont : arrêter les services, interrompre le symlink, déplacer les données du stockage vers le répertoire, puis redémarrer les services.

+
Une fois la sauvegarde NetApp Snapshot non configurée, le mécanisme de sauvegarde change en fonction de la base MySQL par défaut. Cette modification apparaît dans la section sauvegarde de la base de données des paramètres généraux.


