---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Active IQ Unified Manager 9.9
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes.html"
  - title: Commencez
    entries:
    - title: Installation de démarrage rapide pour VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installation de démarrage rapide pour Linux
      url: "/qsg-linux.html"
    - title: Installation de démarrage rapide pour Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Mentions légales
    url: "/legal-notices.html"
