---
permalink: qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Guide de démarrage rapide pour Unified Manager sur plate-forme Linux. 
---
= Instructions de démarrage rapide pour les installations Linux
:allow-uri-read: 




== Configuration minimale requise

* Système d'exploitation : Red Hat Enterprise Linux et CentOS version 7.x et 8.x, basé sur l'architecture x86_64, installés à l'aide de l'environnement de base « Server with GUI » de l'option Software Selection du programme d'installation du système d'exploitation
* RAM : 12 Go, CPU : 9572 MHz au total
* Espace disque libre : 100 Go d'espace disque dans le répertoire /opt/netapp/data, 50 Go dans la partition racine. Pour les répertoires /opt et /var/log montés séparément, assurez-vous que /opt dispose de 15 Go, /var/log de 16 Go et /tmp dispose de 10 Go d'espace libre


Pour obtenir des informations détaillées sur la configuration système requise et sur l'installation du produit sur un site sécurisé, reportez-vous au link:./install-linux/concept-requirements-for-installing-unified-manager.html["Conditions requises pour l'installation de Unified Manager"] et le link:http://mysupport.netapp.com/matrix["Matrice d'interopérabilité"].



== Installation de Active IQ Unified Manager



=== Téléchargez le programme d'installation

. Téléchargez le `ActiveIQUnifiedManager-<version>.zip` package d'installation.
. Dans le répertoire dans lequel vous avez téléchargé le fichier d'installation, exécutez :


`# unzip ActiveIQUnifiedManager-<version>.zip`



=== Vérifiez la configuration du référentiel

Les procédures de configuration des référentiels Red Hat Enterprise Linux ou CentOS sont spécifiques au site. Vous pouvez utiliser le `pre_install_check.sh` script inclus dans le package d'installation pour vérifier la configuration de votre système d'exploitation. Si votre système est connecté à Internet, vous recevez automatiquement les instructions de configuration des référentiels Red Hat Enterprise Linux ou CentOS.

`# sudo ./pre_install_check.sh`



=== Installez Unified Manager

Unified Manager utilise le `yum` utilitaire permettant d'installer le logiciel et tout logiciel dépendant. Étant donné qu'il existe différentes images de Red Hat Enterprise Linux ou CentOS, les packages installés dépendent du logiciel présent dans les images. Le `yum` utilitaire détermine les progiciels dépendants à installer. Si vous avez besoin de plus d'informations sur les progiciels dépendants, reportez-vous à la section link:./install-linux/reference-red-hat-and-centos-software-and-installation-requirements.html["Conditions requises pour l'installation et le logiciel Linux"].

Pour installer Unified Manager, exécutez la commande suivante, soit en tant qu'utilisateur root, soit en utilisant `sudo`, dans le répertoire où le fichier d'installation a été décompressé :

`# yum install netapp-um<version>.x86_64.rpm`

ou

`% sudo yum install netapp-um<version>.x86_64.rpm`

À la fin de l'installation, les informations de connexion à l'interface utilisateur Web de Unified Manager sont affichées. Si vous ne parvenez pas à vous connecter à l'interface utilisateur Web, reportez-vous à la section `README` fichier fourni avec le logiciel pour plus d'informations sur les restrictions du port 443.
