---
permalink: install-vapp/task-downloading-the-unified-manager-ova-file.html 
sidebar: sidebar 
keywords:  
summary: 'Téléchargez le fichier d"installation Unified Manager depuis le site de support NetApp pour déployer Unified Manager en tant que dispositif virtuel.' 
---
= Téléchargement du fichier d'installation de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Téléchargez le fichier d'installation Unified Manager depuis le site de support NetApp pour déployer Unified Manager en tant que dispositif virtuel.



== Avant de commencer

Vous devez disposer des identifiants de connexion pour le site du support NetApp.



== Description de la tâche

Le fichier d'installation est un `OVA` Fichier qui contient le logiciel Unified Manager configuré dans une appliance virtuelle.



== Étapes

. Connectez-vous au site de support NetApp et accédez à la page *Download* pour Unified Manager : https://["Site de support NetApp"]
. Sélectionnez la version requise de Unified Manager et acceptez le contrat de licence utilisateur final (CLUF).
. Téléchargez et enregistrez `OVA` Fichier pour l'installation de VMware vSphere dans un répertoire local ou un répertoire réseau accessible à votre client vSphere.
. Vérifiez la somme de contrôle pour vous assurer que le logiciel a été correctement téléchargé.

