---
permalink: install-vapp/task-upgrading-the-unified-manager-virtual-appliance-vapp.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez mettre à niveau l"appliance virtuelle Unified Manager des versions 9.7 et 9.8 vers la version 9.9.' 
---
= Mise à niveau de l'appliance virtuelle Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau l'appliance virtuelle Unified Manager des versions 9.7 et 9.8 vers la version 9.9.



== Avant de commencer

Vérifiez les points suivants :

* Vous avez téléchargé le fichier de mise à niveau, le `ISO` Image du site de support NetApp.
* Le système sur lequel vous mettez à niveau Unified Manager répond à la configuration système et logicielle requise.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Besoins de l'infrastructure virtuelle]

+
xref:reference-vmware-software-and-installation-requirements.adoc[Conditions requises pour le logiciel VMware et son installation]

* Pour les utilisateurs de vSphere 6.5 et des versions ultérieures, vous avez installé VMware Remote Console (VMRC).
* Lors d'une mise à niveau, vous pouvez être invité à confirmer si vous souhaitez conserver les paramètres par défaut précédents pour conserver les données de performances pendant 13 mois ou à les modifier à 6 mois. A la confirmation, les données historiques de performance sont supprimées au bout de 6 mois.
* Vous disposez des informations suivantes :
+
** Identifiants de connexion pour le site du support NetApp
** Informations d'identification pour l'accès à VMware vCenter Server et au client Web vSphere
** Informations d'identification pour l'utilisateur responsable de la maintenance Unified Manager






== Description de la tâche

Unified Manager n'est pas disponible lors du processus de mise à niveau. Pour effectuer toute opération en cours d'exécution, vous devez effectuer la mise à niveau de Unified Manager.

Si vous avez associé Workflow Automation et Unified Manager, vous devez mettre à jour manuellement le nom d'hôte dans Workflow Automation.



== Étapes

. Dans vSphere client, cliquez sur *Accueil* > *Inventaire* > *VM et modèles*.
. Sélectionnez la machine virtuelle (VM) sur laquelle l'appliance virtuelle Unified Manager est installée.
. Si la machine virtuelle Unified Manager est en cours d'exécution, accédez à *Résumé* > *commandes* > *Arrêter invité*.
. Créer une copie de sauvegarde, par exemple une copie Snapshot ou un clone, de la machine virtuelle Unified Manager pour créer une sauvegarde cohérente avec les applications.
. À partir du client vSphere, mettez la machine virtuelle sous tension.
. Lancez la console à distance VMware.
. Cliquez sur l'icône *CDROM* et sélectionnez *connexion au fichier image disque (.iso)*.
. Sélectionner `ActiveIQUnifiedManager-<version>-virtual-update.iso` Et cliquez sur *Ouvrir*.
. Cliquez sur l'onglet *Console*.
. Connectez-vous à la console de maintenance de Unified Manager.
. Dans le *Menu principal*, sélectionnez *mise à niveau*.
+
Un message s'affiche indiquant que Unified Manager doit être indisponible durant la mise à niveau, et qu'il reprend après la fin du processus.

. Type `y` pour continuer.
+
Un avertissement s'affiche, vous rappelant de sauvegarder la machine virtuelle sur laquelle réside l'appliance virtuelle.

. Type `y` pour continuer.
+
Le processus de mise à niveau et le redémarrage des services Unified Manager peuvent prendre plusieurs minutes.

. Appuyez sur n'importe quelle touche pour continuer.
+
Vous êtes automatiquement déconnecté de la console de maintenance.

. Connectez-vous à la console de maintenance, puis vérifiez la version d'Unified Manager.




== Une fois que vous avez terminé

Vous pouvez vous connecter à l'interface utilisateur Web pour utiliser la version mise à niveau d'Unified Manager. Notez que vous devez attendre la fin du processus de détection avant d'effectuer une tâche dans l'interface utilisateur.
