---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez mettre à niveau Unified Manager 9.7 ou 9.8 vers 9.9 en téléchargeant et en exécutant le fichier d"installation sur la plate-forme Windows.' 
---
= Mise à niveau d'Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau Unified Manager 9.7 ou 9.8 vers 9.9 en téléchargeant et en exécutant le fichier d'installation sur la plate-forme Windows.



== Avant de commencer

* Le système sur lequel vous mettez à niveau Unified Manager doit répondre à la configuration système et logicielle requise.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Configuration matérielle requise]

+
xref:reference-windows-software-and-installation-requirements.adoc[Conditions requises pour l'installation et le logiciel Windows]

+
[NOTE]
====
À partir de Unified Manager 9.5, OpenJDK est fourni dans le package d'installation et installé automatiquement. Oracle Java n'est pas pris en charge à partir de Unified Manager 9.5.

====
+
[NOTE]
====
Assurez-vous que Microsoft .NET 4.5.2 ou une version ultérieure est installé sur votre système avant de démarrer la mise à niveau.

====
* MySQL Community Edition est automatiquement mis à niveau lors de la mise à niveau d'Unified Manager. Si la version installée de MySQL sur votre système est antérieure à 8.0.21, le processus de mise à niveau de Unified Manager met automatiquement à niveau MySQL vers 8.0.21. Vous ne devez pas exécuter une mise à niveau autonome d'une version antérieure de MySQL vers 8.0.21. Si la version installée de MySQL sur votre système est 5.7, alors vous devez *pas* essayer de mettre directement à niveau MySQL vers la version 8.0.21. Cela entraîne la perte des données d'application.
+
[NOTE]
====
Le programme d'installation d'Unified Manager a été limité à la prise en charge de MySQL Community Edition 8.0.21, en raison d'un problème d'interopérabilité. Vous ne devez pas mettre à niveau MySQL vers une version supérieure à 8.0.21.

====
* Vous devez disposer des privilèges d'administrateur Windows. Assurez-vous que votre nom d'utilisateur ne commence pas par un point d'exclamation ""!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!».
* Vous devez disposer d'identifiants valides pour vous connecter au site du support NetApp.
* Pour éviter la perte de données, vous devriez avoir créé une sauvegarde de la machine Unified Manager en cas de problème lors de la mise à niveau.
* Vous devez disposer d'un espace disque suffisant pour effectuer la mise à niveau.
+
L'espace disponible sur le lecteur d'installation doit être supérieur de 2.5 Go à la taille du répertoire de données. La mise à niveau s'arrête et affiche un message d'erreur indiquant la quantité d'espace à ajouter si l'espace disponible est insuffisant.

* Lors d'une mise à niveau, vous pouvez être invité à confirmer si vous souhaitez conserver les paramètres par défaut précédents pour conserver les données de performances pendant 13 mois ou à les modifier à 6 mois. A la confirmation, les données historiques de performance au bout de 6 mois sont supprimées.
* Avant de procéder à la mise à niveau, fermez tous les fichiers ou dossiers ouverts dans `<InstallDir\>\JDK` et `MySQL Data Directory`.




== Description de la tâche

Unified Manager n'est pas disponible lors du processus de mise à niveau. Pour effectuer toute opération en cours d'exécution, vous devez effectuer la mise à niveau de Unified Manager.

Si Unified Manager est associé à une instance de OnCommand Workflow Automation et que de nouvelles versions du logiciel sont disponibles pour les deux produits, vous devez déconnecter les deux produits et configurer une nouvelle connexion Workflow Automation après avoir effectué les mises à niveau. Si vous effectuez une mise à niveau vers un seul des produits, vous devez vous connecter à Workflow Automation après la mise à niveau, puis vérifier que les données sont toujours acquises depuis Unified Manager.



== Étapes

. Connectez-vous au site de support NetApp et accédez à la page *Download* pour Unified Manager : https://["Site de support NetApp"]
. Sélectionnez la version requise de Unified Manager et acceptez le contrat de licence utilisateur final (CLUF).
. Téléchargez le fichier d'installation de Unified Manager Windows dans un répertoire cible du système Windows.
. Cliquez avec le bouton droit de la souris et exécutez le programme d'installation de Unified Manager `(.exe)` fichier en tant qu'administrateur.
+
Unified Manager vous invite à message suivant :

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Cliquez sur *Oui*, puis sur *Suivant*.
. Entrez le mot de passe racine MySQL8 défini lors de l'installation, puis cliquez sur *Suivant*.
. Connectez-vous à l'interface utilisateur Web d'Unified Manager et vérifiez le numéro de version.




== Une fois que vous avez terminé

[NOTE]
====
Pour effectuer une mise à niveau silencieuse d'Unified Manager, exécutez la commande suivante : `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====