---
permalink: data-protection/reference-create-storage-virtual-machine-associations-wizard.html 
sidebar: sidebar 
keywords:  
summary: 'L"assistant Créer des pairs de machine virtuelle de stockage vous permet de peer-to-peer de stockage source et cible à utiliser dans les relations de protection SnapMirror et SnapVault.' 
---
= Assistant de création de pairs de machine virtuelle de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'assistant Créer des pairs de machine virtuelle de stockage vous permet de peer-to-peer de stockage source et cible à utiliser dans les relations de protection SnapMirror et SnapVault.



== Sélectionnez Source

Le panneau Sélectionner la source vous permet de sélectionner la machine virtuelle de stockage source ou primaire dans l'homologue de la machine virtuelle de stockage.

* *Tout*
+
Permet de créer un homologue entre une source de VM de stockage et une ou plusieurs machines virtuelles de destination, ou secondaires. Cela signifie que toutes les machines virtuelles de stockage existantes qui nécessitent actuellement une protection, ainsi que toutes les machines virtuelles de stockage créées à l'avenir, sont dotées de la machine virtuelle de stockage de destination spécifiée. Vous pouvez, par exemple, vouloir des applications issues de plusieurs sources situées à différents emplacements sauvegardés sur une ou plusieurs machines virtuelles de stockage de destination sur un emplacement unique.

* *Unique*
+
Permet de créer une machine virtuelle de stockage source spécifique avec une ou plusieurs machines virtuelles de stockage de destination. Par exemple, si vous proposez des services de stockage à de nombreux clients dont les données doivent être séparées les uns des autres, sélectionnez cette option pour associer une source de VM de stockage à une destination de VM de stockage spécifique affectée uniquement à ce client.

* *Aucun (externe)*
+
Vous permet de créer une association entre une VM de stockage source et un volume flexible externe d'une VM de stockage cible.

+
** Storage Virtual machine (SVM)
+
Répertorie les noms de la VM de stockage source disponible

** Cluster
+
Le répertorie les clusters sur lesquels réside chaque machine virtuelle de stockage



* *Permettre ces types de relations*
+
Permet de sélectionner le type de relation de l'association :

+
** SnapMirror
+
Spécifie une relation SnapMirror comme type pair. La sélection de cette option active la réplication des données à partir des sources sélectionnées vers les destinations sélectionnées.

** SnapVault
+
Spécifie une relation SnapVault comme type homologue. La sélection de cette option active les sauvegardes des emplacements principaux sélectionnés vers les emplacements secondaires sélectionnés.







== Sélectionnez destinations de protection

Le panneau Select protection destinations de l'assistant Create Storage Virtual machine Pers vous permet de sélectionner l'emplacement de copie ou de réplication des données. Un homologue ne peut être créé que sur une seule machine virtuelle de stockage de destination par cluster.



== Boutons de commande

Les boutons de commande permettent d'effectuer les tâches suivantes :

* *Suivant*
+
Vous permet d'accéder à la page suivante de l'assistant.

* *Retour*
+
Vous renvoie à la page précédente de l'assistant.

* *Terminer*
+
Applique vos sélections et crée l'association.

* *Annuler*
+
Supprime les sélections et ferme l'assistant Créer des homologues de la machine virtuelle de stockage.


